version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ .Version }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

dockers:
  - image_templates:
      - "ghcr.io/skidoodle/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/skidoodle/{{ .ProjectName }}:latest"

    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "ghcr.io/skidoodle/{{ .ProjectName }}:{{ .Tag }}-arm64"

    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm64

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
